version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /services/x-webhook-rss
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule:
      interval: weekly
